backend:
  name: git-gateway
  branch: main # Verifique se o nome da sua branch no GitHub é 'main' ou 'master'

media_folder: "images" # Onde as fotos do celular serão salvas
public_folder: "/images"

collections:
  - name: "servicos"
    label: "Nossos Serviços"
    folder: "content/servicos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Serviço", name: "title", widget: "string" }
      - { label: "Data da Postagem", name: "date", widget: "datetime" }
      - { label: "Foto do Trabalho", name: "image", widget: "image" }
      - { label: "Descrição Curta", name: "body", widget: "markdown", required: false }

# Configuração visual do painel para evitar erros de estilo
display_url: https://bobeletrica.netlify.app